### ISSUE TITLE
modify orthography profile to account for nasalis sonans

### ISSUE THREAD

**Issue by LinguList** [lexibank/chenhmongmien#15]
We have problems handling vocalic nasals in morphemes like `f ŋ ⁵¹`, also because they are *not* indicated as syllabic nasals in the source. As a result, it seems best to search for all those cases in the data, which have no vowel, but a nasal instead, and convert them to an intermediate representation, such as, e.g., `f */ə ŋ ⁵¹`. This will preserve the information, but help us to handle the data properly.

**Comment by LinguList** [comment]
This makes also sense in alignment analyses, since in many cases, there is a "lento" stage in SEA languages, so `f ə ŋ` occurs in one languages, and `f ŋ` in another one.

**Comment by tresoldi** [comment]
@MacyL and I will be working on it on branch `profile` (https://github.com/lexibank/chenhmongmien/tree/profile)

**Comment by MacyL** [comment]
@LinguList  Suggestion needed.
Now the problems occur in the template alignment stage  (can't recognize  u/ʐʷ as 'nucleus')
ʐ a ³² + **w u/w a ⁵³** i n t + m n t
 **ⁿp u/ʐʷ ¹³ i t
ⁿp u/ʐʷ ¹³ i t**
ts i ⁵⁵ + **t l u/w a ³¹** i n t + i m n t
**w u/w a ⁴²** m n t   
**ⁿp u/lʷ ¹³** i t
[!] k a ¹³ + k ŋ ³¹³ i n t + i t  (MSW: I added the entry as  kŋ³¹³$ in the profile, but the problem is still there)
**d iː u ³³** i n t
**w u/w a ³²** + p ʐ a ŋ ³⁵ m n t + i m n c t

**Comment by LinguList** [comment]
@MacyL, the profile is wrong. I will clarify later. Let me work on it, okay?

**Comment by LinguList** [comment]
I will close this now, we add consistent checks later, and make a specific command.
