### ISSUE TITLE
Sinopy to Linse

### ISSUE THREAD

**Issue by MacyL** [lexibank/chenhmongmien#21]
@LinguList is developing a new package called "linse" which is designed to handle linguistic sequences, can we use linse to check the sequence structure? 
Could you, @LinguList show me how to check the syllabic structure of Hmong-Mien languages with linse package?

**Comment by LinguList** [comment]
see ratliff, I will push it now.

**Comment by MacyL** [comment]
I would like to follow the template in ratliffhmongmien and modify the check_structure.py

**Comment by LinguList** [comment]
@MacyL, I discussed this with @xrotwang yesterday: we want to make a new package, which we then call "lexicheck" or "lexibench", from which additional tests can be done, also with additional dependencies. @xrotwang will show how to make an initial structure for such a package, and it would work like:

```
$ cldfbench lexicheck.seallables DATASET
```

This will be the most consistent approach: no more individual copy-pasted code, we can just use one package. 

If you want to already check linse, etc., I recommend to add a folder `examples` to chenhmongmien, where you use pure Python to check with linse, so you don't use the `commands`, because they will then throw errors and warnings if one has not all dependencies installed, which can be a bit annoying. In this way, we can also leave chenhmongmiencommands untouched, for the time being, as this is part of the tutorial as well...

**Comment by MacyL** [comment]
I see :D

**Comment by LinguList** [comment]
BTW: if you write a script in an `example` folder, it it may be helpful to just use UnicodeDictReader to assess the data in CLDF format, etc. You don't need lingpy, and you rather don't use it, as we want to work towards some lingpy3 soon.
